apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
  namespace: default
data:
  config: |- 
    hello: world
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map-2
  namespace: default
data:
  config: |- 
    hello: world