apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{ .Values.commonLabels | toYaml | nindent 4 }}
  name: my-config-map
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "files/ingress-nginx/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels: {{ .Values.commonLabels | toYaml | nindent 4 }}
  name: my-config-map-2
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "files/ingress-nginx/*").AsConfig | indent 2 }}