{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ .Values.commonLabels | toYaml | nindent 4 }}
  name: my-secret-1
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "files/secret/*").AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  labels: {{ .Values.commonLabels | toYaml | nindent 4 }}
  name: my-secret-2
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "files/secret/*").AsSecrets | indent 2 }}
{{- end }}